services:
  backend:
    image: backend:dev
    container_name: back
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      app_net:
        ipv4_address: 172.16.238.10
  front_reactjs:
    image: sample:dev
    container_name: front
    build:
      context: ./react-api
      dockerfile: Dockerfile
    environment:
      - REACT_APP_API=http://172.16.238.10:5000/api/
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      app_net:
        ipv4_address: 172.16.238.12
networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"