## test1

#- name: insert trololo 3
#  lineinfile: dest=/etc/trololo state=present regexp="{{ trololo }}" insertafter="trololo" line="trololo"
#  notify: restart trololo

- name: insert trololo 3
  lineinfile: dest=/etc/trololo state=present regexp="{{ trololo }}" insertafter="trololo" line="trololo1"
  notify: restart trololo

- name: space in args module bug
  lineinfile:                                                                                                  
    dest: /etc/trololo
    regexp: {{ trololo_ trololo }}
    line: wtf
    state: present

- name: insert trololo
  lineinfile:
    dest: /etc/trololo
    regexp: "{{ trololo }}"
    state: present
    line: trololo
    insertafter: trololo
  notify: restart trololo
